name: Supabase Migrations

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'ritter-app/supabase/migrations/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link project
        run: supabase link --project-ref teiyrvoisdzvttrqslgk
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        working-directory: ritter-app

      - name: Push migrations
        run: supabase db push --db-url "${{ secrets.SUPABASE_DB_URL }}"
        working-directory: ritter-app
